class_order:
  0: struktur_penyangga
  1: konduktor
  2: pohon_sono
aliases:
  struktur_penyangga: [P001_struktur_penyangga, pole, tiang]
  konduktor: [K001_konduktor, conductor, cable, kabel]
  pohon_sono: [V001_pohon_sono, tree canopy, vegetation]
policy:
  no_fake_label: true
  no_class_order_change: true
